version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
      day: friday
      time: "20:00"
      timezone: Europe/Amsterdam
    open-pull-requests-limit: 20
    reviewers:
      - s-weigand
    assignees:
      - s-weigand
    groups:
      runtime-dependencies:
        update-types:
          - minor
          - patch
    rebase-strategy: "disabled"

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: friday
      time: "20:00"
      timezone: Europe/Amsterdam
    reviewers:
      - s-weigand
    assignees:
      - s-weigand
    groups:
      GH-Actions:
        update-types:
          - minor
          - patch
    rebase-strategy: "disabled"
