repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0-alpha.9-for-vscode
    hooks:
      - id: prettier
        additional_dependencies:
          - 'prettier@2.8.8'
          - '@trivago/prettier-plugin-sort-imports@v4.1.1'

  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.4
    hooks:
      - id: codespell
        files: '\.(html|tsx?|s?css|md)$'

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.39.0
    hooks:
      - id: eslint
        types: [file] # override `types: [javascript]`
        files: \.(tsx?)$
        args: [--ext, '.ts,.tsx']
        additional_dependencies:
          - 'eslint@8.39.0'
          - 'typescript@5.0.4'
          - '@typescript-eslint/eslint-plugin@5.59.1'
          - '@typescript-eslint/parser@5.59.1'
          - 'eslint-config-prettier@8.8.0'
          - 'eslint-plugin-import@2.27.5'
          - 'eslint-plugin-prettier@4.2.1'
          - 'prettier@2.8.8'
