repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.3.0
    hooks:
      - id: prettier

  - repo: https://github.com/codespell-project/codespell
    rev: v2.0.0
    hooks:
      - id: codespell
        files: '\.(html|tsx?|s?css|md)$'

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v7.27.0
    hooks:
      - id: eslint
        types: [file] # override `types: [javascript]`
        files: \.(tsx?)$
        args: [--ext, '.ts,.tsx']
        additional_dependencies:
          - 'eslint@7.27.0'
          - 'typescript@4.2.4'
          - '@typescript-eslint/eslint-plugin@4.25.0'
          - '@typescript-eslint/parser@4.25.0'
          - 'eslint-config-prettier@8.3.0'
          - 'eslint-plugin-import@2.23.3'
          - 'eslint-plugin-prettier@3.4.0'
          - 'prettier@2.3.0'
