repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0-alpha.4
    hooks:
      - id: prettier

  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.2
    hooks:
      - id: codespell
        files: '\.(html|tsx?|s?css|md)$'

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.26.0
    hooks:
      - id: eslint
        types: [file] # override `types: [javascript]`
        files: \.(tsx?)$
        args: [--ext, '.ts,.tsx']
        additional_dependencies:
          - 'eslint@8.26.0'
          - 'typescript@4.8.4'
          - '@typescript-eslint/eslint-plugin@4.25.0'
          - '@typescript-eslint/parser@5.42.0'
          - 'eslint-config-prettier@8.5.0'
          - 'eslint-plugin-import@2.26.0'
          - 'eslint-plugin-prettier@4.2.1'
          - 'prettier@3.0.0-alpha.4'
