name: Build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
      - name: Run pre-commit
        uses: pre-commit/action@v2.0.3

  build:
    needs: [pre-commit]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install node
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - name: Setup npm cache
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            npm-
      - name: Install dependencies
        run: |
          npm ci
      - name: Build Github-Pages
        run: |
          npm run gh-pages

      - name: Upload bundled page
        if: success()
        uses: actions/upload-artifact@v2
        with:
          name: deploy
          path: deploy

  deploy-page:
    if: github.event_name == 'push' && github.event.ref == 'refs/heads/main'
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Download  bundled page
        uses: actions/download-artifact@v2
        with:
          name: deploy
          path: deploy

      - name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
