name: Build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Run pre-commit
        uses: pre-commit/action@v3.0.0

  build:
    needs: [pre-commit]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Setup npm cache
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            npm-
      - name: Install npm dependencies
        run: |
          npm ci

      - name: Install python dependencies
        run: |
          python -m pip install -U pip wheel
          python -m pip install -r utils/requirements.txt

      - name: Build Github-Pages
        run: |
          npm run gh-pages

      - name: Show index.html
        run: |
          python utils/post_build.py pretty-print

      - name: Upload bundled page
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: deploy
          path: deploy

  deploy-page:
    if: github.event_name == 'push' && github.event.ref == 'refs/heads/main'
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Download  bundled page
        uses: actions/download-artifact@v3
        with:
          name: deploy
          path: deploy

      - name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: gh-pages
          build_dir: deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
