name: Build

on:
  push:
    branches-ignore:
      - "dependabot/**"
  pull_request:
  workflow_dispatch:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Run pre-commit
        uses: pre-commit/action@v3.0.1

  build:
    needs: [pre-commit]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"

      - name: Setup npm cache
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            npm-

      - name: Install npm dependencies
        run: |
          npm ci

      - name: Check typing
        run: |
          npm run check-types

      - name: Build Github-Pages
        run: |
          npm run gh-pages

      - name: Upload bundled page
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: deploy
          path: deploy

      - name: Install uv
        if: github.event_name == 'pull_request'
        uses: astral-sh/setup-uv@v5

      - name: Build preview
        if: github.event_name == 'pull_request'
        run: |
          npm run clean
          npm run build

      - name: Upload page preview
        if: github.event_name == 'pull_request'
        env:
          SMOKESHOW_GITHUB_STATUS_DESCRIPTION: Preview
          SMOKESHOW_AUTH_KEY: ${{ secrets.SMOKESHOW_AUTH_KEY }}
          SMOKESHOW_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SMOKESHOW_GITHUB_PR_HEAD_SHA: ${{ github.event.pull_request.head.sha }}
        run: |
          uvx smokeshow upload deploy

  deploy-page:
    if: github.event_name == 'push' && github.event.ref == 'refs/heads/main'
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Download  bundled page
        uses: actions/download-artifact@v4
        with:
          name: deploy
          path: deploy

      - name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: gh-pages
          build_dir: deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
